server:
  port: 8000
  # {@link https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/Undertow.java}
  undertow:
    # Size of each buffer in bytes.
    buffer-size: 1024
    # Allocate buffers outside the Java heap. The default is derived from the maximum amount of memory that is available to the JVM.
    direct-buffers: true
    # Number of I/O threads to create for the worker. The default is derived from the number of available processors.
    io-threads: 16
    # Number of worker threads. The default is 8 times the number of I/O threads.
    worker-threads: 256
spring:
  application:
    name: esportingplus-monitor-server
  profiles:
    active: @profile.env@

management:
  security:
    enabled: false

security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}

---
spring:
  profiles: dev
  mail:
    host: smtp.qq.com
    port: 25
    username: 254827219@qq.com
    password: ldterppywihtbhde
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: 254827219@qq.com
          to: 254827219@qq.com

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/

---
spring:
  profiles: test
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    protocol: ${mail.protocol}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          ssl:
            enable: ${mail.smtp.ssl.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  boot:
    admin:
      notify:
        mail:
          from: ${mail.from}
          to: ${mail.to}

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

---
spring:
  profiles: test3
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    protocol: ${mail.protocol}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          ssl:
            enable: ${mail.smtp.ssl.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  boot:
    admin:
      notify:
        mail:
          from: ${mail.from}
          to: ${mail.to}

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

---
spring:
  profiles: grey
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    protocol: ${mail.protocol}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          ssl:
            enable: ${mail.smtp.ssl.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  boot:
    admin:
      notify:
        mail:
          from: ${mail.from}
          to: ${mail.to}

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

---
spring:
  profiles: load
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    protocol: ${mail.protocol}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          ssl:
            enable: ${mail.smtp.ssl.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  boot:
    admin:
      notify:
        mail:
          from: ${mail.from}
          to: ${mail.to}

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}

---
spring:
  profiles: prod
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          ssl:
            enable: ${mail.smtp.ssl.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  boot:
    admin:
      notify:
        mail:
          from: ${mail.from}
          to: ${mail.to}

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}


---
spring:
  profiles: prod2
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: ${mail.smtp.auth}
          ssl:
            enable: ${mail.smtp.ssl.enable}
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
  boot:
    admin:
      notify:
        mail:
          from: ${mail.from}
          to: ${mail.to}

eureka:
  instance:
    #hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}